name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo rsync -av --delete ./ /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo systemctl restart apache2
